# Generated by Django 3.2.12 on 2022-03-22 16:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='content',
            field=ckeditor.fields.RichTextField(max_length=4096),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=512),
        ),
    ]
